# report_generator.py
# ---------------------------------------------------------------------------
# This file takes the raw AI-generated text from Groq
# and structures it into a clean, organized report object.
#
# Why do we need this?
# - Groq gives us raw markdown text
# - We need to parse it into sections
# - We add metadata (date, document names, etc.)
# - We prepare it for both Streamlit display and PDF export
# ---------------------------------------------------------------------------

import re                    # For pattern matching in text (regex)
from datetime import datetime  # For adding current date to report
from config import REPORT_TITLE, APP_NAME, REPORT_SECTIONS


def get_current_datetime() -> str:
    """
    Returns current date and time as a formatted string.
    Example output: "April 03, 2026 at 10:30 AM"
    """
    # strftime formats the date - %B = full month name, %d = day, %Y = year
    return datetime.now().strftime("%B %d, %Y at %I:%M %p")


def parse_report_sections(report_text: str) -> dict:
    """
    Splits the AI-generated report text into individual sections.
    
    The AI generates markdown text like:
    ## Executive Summary
    Some text here...
    
    ## Document 1 Overview
    More text here...
    
    We split this into a dictionary like:
    {
        "Executive Summary": "Some text here...",
        "Document 1 Overview": "More text here...",
        ...
    }
    
    Returns:
    - Dictionary with section names as keys and content as values
    """
    
    sections = {}
    
    # Split the text by lines starting with ##
    # re.split() splits a string based on a pattern
    # r"(?=^##\s)" means "split at positions where ## appears at start of line"
    # re.MULTILINE makes ^ match start of each line
    parts = re.split(r"(?=^##\s)", report_text, flags=re.MULTILINE)
    
    for part in parts:
        part = part.strip()
        if not part:
            continue
        
        # Check if this part starts with ##
        if part.startswith("##"):
            # Split into header and content
            lines = part.split("\n", 1)   # Split at first newline only
            
            if len(lines) >= 1:
                # Clean up the section header
                # Remove ## and strip whitespace
                header = lines[0].replace("##", "").strip()
                
                # Get the content (everything after the header)
                content = lines[1].strip() if len(lines) > 1 else ""
                
                # Store in dictionary
                sections[header] = content
        else:
            # Text before any ## header (intro text)
            if part:
                sections["Introduction"] = part
    
    return sections


def build_report_object(report_text: str, doc1_info: dict, doc2_info: dict) -> dict:
    """
    Creates a complete structured report object with all metadata.
    
    This combines:
    - The AI-generated content
    - Document information (names, pages, etc.)
    - Report metadata (date, title, etc.)
    
    Returns:
    - A dictionary with everything needed to display and export the report
    """
    
    # Parse the raw text into sections
    sections = parse_report_sections(report_text)
    
    # Build the complete report object
    report = {
        # Report metadata
        "title": REPORT_TITLE,
        "generated_by": APP_NAME,
        "generated_at": get_current_datetime(),
        
        # Document information
        "document_1": {
            "name": doc1_info["file_name"],
            "pages": doc1_info["pages"],
            "author": doc1_info["author"],
            "title": doc1_info["title"],
            "size_kb": doc1_info["file_size_kb"]
        },
        "document_2": {
            "name": doc2_info["file_name"],
            "pages": doc2_info["pages"],
            "author": doc2_info["author"],
            "title": doc2_info["title"],
            "size_kb": doc2_info["file_size_kb"]
        },
        
        # The actual report content (sections from AI)
        "sections": sections,
        
        # Raw text (useful for debugging)
        "raw_text": report_text
    }
    
    return report


def format_report_for_display(report: dict) -> str:
    """
    Converts the report object to a nicely formatted markdown string
    for displaying in Streamlit.
    
    Streamlit can render markdown directly using st.markdown()
    
    Returns:
    - Formatted markdown string
    """
    
    lines = []
    
    # Report header
    lines.append(f"# {report['title']}")
    lines.append(f"*Generated by {report['generated_by']} on {report['generated_at']}*")
    lines.append("")  # Empty line for spacing
    
    # Document information box
    lines.append("---")
    lines.append("### 📄 Documents Analyzed")
    lines.append(f"**Document 1:** {report['document_1']['name']} ({report['document_1']['pages']} pages)")
    lines.append(f"**Document 2:** {report['document_2']['name']} ({report['document_2']['pages']} pages)")
    lines.append("---")
    lines.append("")
    
    # Add each section
    for section_name, content in report["sections"].items():
        lines.append(f"## {section_name}")
        lines.append(content)
        lines.append("")  # Empty line between sections
    
    return "\n".join(lines)


def format_report_for_pdf(report: dict) -> str:
    """
    Converts the report object to plain text format for PDF generation.
    
    PDF generation works with plain text/HTML, not markdown.
    So we convert markdown formatting to plain text here.
    
    Returns:
    - Plain text version of the report
    """
    
    lines = []
    
    # Title
    lines.append(report["title"].upper())
    lines.append(f"Generated by: {report['generated_by']}")
    lines.append(f"Date: {report['generated_at']}")
    lines.append("=" * 60)
    lines.append("")
    
    # Document info
    lines.append("DOCUMENTS ANALYZED")
    lines.append("-" * 40)
    lines.append(f"Document 1: {report['document_1']['name']}")
    lines.append(f"Pages: {report['document_1']['pages']}")
    lines.append("")
    lines.append(f"Document 2: {report['document_2']['name']}")
    lines.append(f"Pages: {report['document_2']['pages']}")
    lines.append("")
    lines.append("=" * 60)
    lines.append("")
    
    # Sections
    for section_name, content in report["sections"].items():
        lines.append(section_name.upper())
        lines.append("-" * 40)
        
        # Remove markdown formatting from content
        # Replace **bold** with just the word
        clean_content = re.sub(r"\*\*(.*?)\*\*", r"\1", content)
        # Replace ### headers with plain text
        clean_content = re.sub(r"###\s*(.*)", r"\1:", clean_content)
        # Remove remaining # symbols
        clean_content = re.sub(r"#+ ", "", clean_content)
        
        lines.append(clean_content)
        lines.append("")
    
    return "\n".join(lines)
